name: Documentation
on: [ push, pull_request, workflow_dispatch ]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo sphinx-copybutton sphinxext-opengraph myst-parser autodoc_pydantic pandoc nbsphinx
          sudo apt-get install pandoc
      - name: Build and Commit
        uses: sphinx-notes/pages@master
        with:
          documentation_path: docs
          install_requirements: "true"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SPHINX_DOCUMENTATION }}
          branch: gh-pages