name: Documentation
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo sphinx-copybutton sphinxext-opengraph myst-parser autodoc_pydantic nbsphinx
          sudo apt-get install pandoc
      - name: Build and Commit
        uses: sphinx-notes/pages@master
        with:
          documentation_path: "./docs"
          install_requirements: "true"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SPHINX_DOCUMENTATION }}
          branch: gh-pages